### ISSUE TITLE
nginx源码学习

### ISSUE THREAD

**Issue by Yikun** [Yikun/yikun.github.com#1]
第一阶段 看代码 2014.03～2013.04

| 事项 | 时间 |  
|-----------|----------------|  
| ~~1.初始化过程~~| 2014.03～2013.04 |
| ~~2.master与worker的通信机制~~| 2014.03～2013.04 |
|~~3.nginx事件模型的初始化~~|2014.03～2013.04|
|~~4.nginx事件驱动模型~~|2014.04.01~2014.04.06|
|~~5.listening-->accept~~|2014.04.01~2014.04.06|
|~~6.nginx连接池的实现~~|2014.04|
|7.nginx内存池的实现|2014.04|
|8.nginx的基本数据结构|2014.04|

TODO
7.nginx配置解析过程
8.熟悉nginx模块开发
https://code.google.com/p/nginxsrp/wiki/NginxCodeReview
http://www.yaoweibin.cn/maindoc/nginx-modules-guide-cn.pdf
http://www.evanmiller.org/nginx-modules-guide.html

10.红黑树的管理

**Comment by Yikun** [comment]
Git

**Comment by Yikun** [comment]
tes

**Comment by Yikun** [comment]
github issue + hexo + [gitment](https://github.com/imsun/gitment) + [hexo-migrator-github-issue](https://github.com/Yikun/hexo-migrator-github-issue)

**Comment by imangry** [comment]
学长 好厉害

**Comment by CHEATBEATER** [comment]
首次在网上发现我司同事的博客...

**Comment by 9hao** [comment]
v2ex看了链接，没想到是熟人，啊哈哈

**Comment by Yikun** [comment]
@9hao 木有猜到你是谁。。。

**Comment by Yikun** [comment]
@CHEATBEATER 共勉！哈哈

**Comment by WxFang** [comment]
看Java文章找到的博客，没想到是西电学长哈哈哈，看看感觉好惭愧啊

**Comment by imangry** [comment]
佩服学长。

**Comment by InsaneYoungStunner** [comment]
cloudBu的大神

**Comment by Yikun** [comment]
分页测试

**Comment by Embedded-Chiangdi** [comment]
看完太惭愧了
