### ISSUE TITLE
如果我在这里open 一个issue

### ISSUE THREAD

**Issue by bylion** [Yikun/yikun.github.com#55]
你那个自动sync up的插件是不是也会 把我的写的sync up到你的github.io page?

ps: 只是刚好在研究你怎么用issue发布文章的  没有恶意， 请close掉这个issue as you want. 

好喜欢你的文章 写得明了  而且条理清晰

**Comment by Yikun** [comment]
@bylion 是的，不过sync是手动触发的 ：），更新的[脚本](https://github.com/Yikun/yikun.github.com/blob/hexo/update.sh)可以参考这里，用的是[hexo-migrator-github-issue插件](https://github.com/Yikun/hexo-migrator-github-issue)
